apiVersion: v1
items:
- apiVersion: node.k8s.io/v1
  handler: kata
  kind: RuntimeClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"node.k8s.io/v1","handler":"kata","kind":"RuntimeClass","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"kata-vm-isolation"},"overhead":{"podFixed":{"memory":"600Mi"}},"scheduling":{"nodeSelector":{"kubernetes.azure.com/kata-vm-isolation":"true"}}}
    creationTimestamp: "2026-05-20T19:23:32Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/cluster-service: "true"
    name: kata-vm-isolation
    resourceVersion: "724"
    uid: c6bd5646-3207-42a9-8da2-3dd803a6a913
  overhead:
    podFixed:
      memory: 600Mi
  scheduling:
    nodeSelector:
      kubernetes.azure.com/kata-vm-isolation: "true"
- apiVersion: node.k8s.io/v1
  handler: runc
  kind: RuntimeClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"node.k8s.io/v1","handler":"runc","kind":"RuntimeClass","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"runc"}}
    creationTimestamp: "2026-05-20T19:23:32Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/cluster-service: "true"
    name: runc
    resourceVersion: "723"
    uid: 6470107f-c789-40b8-99af-2f7d3884545e
kind: List
metadata:
  resourceVersion: ""
