apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"azure.workload.identity/use":"true"},"name":"kimi-demo","namespace":"demo"},"spec":{"containers":[{"command":["python3","/code/run.py"],"image":"mcr.microsoft.com/azurelinux/base/python:3.12","name":"runner","volumeMounts":[{"mountPath":"/code","name":"code"}]}],"nodeSelector":{"sandbox.io/runtime":"kata"},"restartPolicy":"Never","runtimeClassName":"kata-vm-isolation","serviceAccountName":"kimi-sa","tolerations":[{"effect":"NoSchedule","key":"runtime","operator":"Equal","value":"kata"}],"volumes":[{"configMap":{"name":"kimi-demo-code"},"name":"code"}]}}
  creationTimestamp: "2026-05-20T21:14:35Z"
  generation: 1
  labels:
    azure.workload.identity/use: "true"
  name: kimi-demo
  namespace: demo
  resourceVersion: "40814"
  uid: 02ce7b4d-d797-4273-8374-05e66b92be5a
spec:
  containers:
  - command:
    - python3
    - /code/run.py
    env:
    - name: AZURE_CLIENT_ID
      value: 71c25413-b3ff-4d65-8236-240ed20d2201
    - name: AZURE_TENANT_ID
      value: 16b3c013-d300-468d-ac64-7eda0820b6d3
    - name: AZURE_FEDERATED_TOKEN_FILE
      value: /var/run/secrets/azure/tokens/azure-identity-token
    - name: AZURE_AUTHORITY_HOST
      value: https://login.microsoftonline.com/
    image: mcr.microsoft.com/azurelinux/base/python:3.12
    imagePullPolicy: IfNotPresent
    name: runner
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /code
      name: code
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-ldk9j
      readOnly: true
    - mountPath: /var/run/secrets/azure/tokens
      name: azure-identity-token
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-kata-82442390-vmss000001
  nodeSelector:
    kubernetes.azure.com/kata-vm-isolation: "true"
    sandbox.io/runtime: kata
  overhead:
    memory: 600Mi
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  runtimeClassName: kata-vm-isolation
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: kimi-sa
  serviceAccountName: kimi-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: runtime
    operator: Equal
    value: kata
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: kimi-demo-code
    name: code
  - name: kube-api-access-ldk9j
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
  - name: azure-identity-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: api://AzureADTokenExchange
          expirationSeconds: 3600
          path: azure-identity-token
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-05-20T21:14:56Z"
    observedGeneration: 1
    status: "False"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-05-20T21:14:36Z"
    observedGeneration: 1
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-05-20T21:14:50Z"
    observedGeneration: 1
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-05-20T21:14:50Z"
    observedGeneration: 1
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-05-20T21:14:35Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://07d8aefbf8f73817d825103c18741cecffed03e23ae9a43ac36e1c731bec0877
    image: mcr.microsoft.com/azurelinux/base/python:3.12
    imageID: mcr.microsoft.com/azurelinux/base/python@sha256:485299b016fe5ae745ffee27f0b8a850576841205ed1d420c9a84b126198e320
    lastState: {}
    name: runner
    ready: false
    resources: {}
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://07d8aefbf8f73817d825103c18741cecffed03e23ae9a43ac36e1c731bec0877
        exitCode: 0
        finishedAt: "2026-05-20T21:14:49Z"
        reason: Completed
        startedAt: "2026-05-20T21:14:37Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /code
      name: code
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-ldk9j
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /var/run/secrets/azure/tokens
      name: azure-identity-token
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.10.2.19
  hostIPs:
  - ip: 10.10.2.19
  observedGeneration: 1
  phase: Succeeded
  podIP: 10.10.2.45
  podIPs:
  - ip: 10.10.2.45
  qosClass: BestEffort
  startTime: "2026-05-20T21:14:36Z"
