apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-05-20T22:42:31Z"
  generateName: 0cbc643d-2fca-47b7-94cf-9ef1b43a223b-
  generation: 1
  labels:
    batch-sandbox.sandbox.opensandbox.io/name: 0cbc643d-2fca-47b7-94cf-9ef1b43a223b
    batch-sandbox.sandbox.opensandbox.io/pod-index: "0"
    opensandbox.io/id: 0cbc643d-2fca-47b7-94cf-9ef1b43a223b
  name: 0cbc643d-2fca-47b7-94cf-9ef1b43a223b-0
  namespace: opensandbox
  ownerReferences:
  - apiVersion: sandbox.opensandbox.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: BatchSandbox
    name: 0cbc643d-2fca-47b7-94cf-9ef1b43a223b
    uid: 72ec73da-2b4c-40a5-bebf-b6eba14fc5a1
  resourceVersion: "73172"
  uid: c98162ca-6525-4d67-9be5-168e7de6172a
spec:
  containers:
  - command:
    - /opt/opensandbox/bin/bootstrap.sh
    - tail
    - -f
    - /dev/null
    env:
    - name: EXECD
      value: /opt/opensandbox/bin/execd
    image: python:3.12-slim
    imagePullPolicy: IfNotPresent
    name: sandbox
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/opensandbox/bin
      name: opensandbox-bin
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kjfhx
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - cp ./execd /opt/opensandbox/bin/execd && cp ./bootstrap.sh /opt/opensandbox/bin/bootstrap.sh
      && chmod +x /opt/opensandbox/bin/execd && chmod +x /opt/opensandbox/bin/bootstrap.sh
    command:
    - /bin/sh
    - -c
    image: acropensandboxdemo7075.azurecr.io/opensandbox/execd:v1.0.7
    imagePullPolicy: IfNotPresent
    name: execd-installer
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/opensandbox/bin
      name: opensandbox-bin
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kjfhx
      readOnly: true
  nodeName: aks-nodepool1-13814532-vmss000002
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - emptyDir: {}
    name: opensandbox-bin
  - name: kube-api-access-kjfhx
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-05-20T22:42:31Z"
    observedGeneration: 1
    status: "False"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-05-20T22:42:31Z"
    message: 'containers with incomplete status: [execd-installer]'
    observedGeneration: 1
    reason: ContainersNotInitialized
    status: "False"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-05-20T22:42:31Z"
    message: 'containers with unready status: [sandbox]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-05-20T22:42:31Z"
    message: 'containers with unready status: [sandbox]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-05-20T22:42:31Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: python:3.12-slim
    imageID: ""
    lastState: {}
    name: sandbox
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: PodInitializing
    volumeMounts:
    - mountPath: /opt/opensandbox/bin
      name: opensandbox-bin
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kjfhx
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.10.1.10
  hostIPs:
  - ip: 10.10.1.10
  initContainerStatuses:
  - image: acropensandboxdemo7075.azurecr.io/opensandbox/execd:v1.0.7
    imageID: ""
    lastState: {}
    name: execd-installer
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: PodInitializing
    volumeMounts:
    - mountPath: /opt/opensandbox/bin
      name: opensandbox-bin
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kjfhx
      readOnly: true
      recursiveReadOnly: Disabled
  observedGeneration: 1
  phase: Pending
  qosClass: Burstable
  startTime: "2026-05-20T22:42:31Z"
