[server]
host = "0.0.0.0"
port = 80
api_key = ""

[log]
level = "INFO"

[runtime]
type = "kubernetes"
execd_image = "acropensandboxdemo7075.azurecr.io/opensandbox/execd:v1.0.8"

[kubernetes]
kubeconfig_path = "/mnt/kube/kubeconfig"
namespace = "opensandbox"
informer_enabled = true
informer_resync_seconds = 300

[ingress]
mode = "direct"
